artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  sas: research/a2z_insurance.sas7bdat
  csv: artifacts/data_ingestion/data.csv
  
data_transformation: 
  root_dir: artifacts/data_transformation
  transformed_data_path: artifacts/data_transformation/transformed_data.pkl
  transformer_path : artifacts/data_transformation/transformer.pkl
  metric_features : ['FirstPolYear', 'BirthYear', 'MonthSal', 'CustMonVal', 'ClaimsRate', 'PremMotor', 'PremHousehold', 'PremHealth', 'PremLife', 'PremWork']
  non_metric_features : ['EducDeg', 'GeoLivArea', 'Children']
  
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pkl
  # updated_base_model_path: artifacts/prepare_base_model/updated_base_model.pkl


train_model:
  root_dir: artifacts/train_model
  trained_model_path: artifacts/train_model/model.pkl
  

   