artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  sas: research/a2z_insurance.sas7bdat
  csv: artifacts/data_ingestion/data.csv
  
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pkl
  # updated_base_model_path: artifacts/prepare_base_model/updated_base_model.pkl


    


   